-kategori 1 : Challenge Algoritma
-kategori 2 : Challenge Website (Sudah Berjalan)
-Kategori 3 : Challenge Jaringan
-Kategori 4 : Challenge CTF (Sudah Berjalan)
-Kategori 5 : Challenge Desain dan Animasi
